sonar.projectKey=cafeteria
sonar.projectName=Cafe Verde
sonar.host.url=http://localhost:9000
sonar.sources=backend,frontend/src
sonar.exclusions=**/migrations/**,**/node_modules/**,**/staticfiles/**
sonar.python.version=3.12
